//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using UnityEngine;

namespace AssemblyCSharp
{
	public class Column
	{
		private List<GameObject> gameObjects = new List<GameObject>();

		private int capacity;

		public bool OpenSpaces{ get { return gameObjects.Count > 0; } }

		public void Add(GameObject go)
		{
			go.transform.position = origin;
			gameObjects.Add (go);
		}

		private Vector3 origin;

		public Column(Vector3 origin, int capacity)
		{
			this.capacity = capacity;
			this.origin = origin;
		}
	}
}

