//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using UnityEngine;

namespace AssemblyCSharp
{
	public class Column
	{
		public List<GameObject> NumbersInstantiated{ get; private set; }

		private int capacity;

		public bool OpenSpaces{ get { return NumbersInstantiated.Count < capacity; } }

		public void Add(GameObject go)
		{
			go.transform.position = origin;
			NumbersInstantiated.Add (go);
			NumbersInstantiated.OrderBy(n => n.transform.position.y);
		}

		private Vector3 origin;

		public Column(Vector3 origin, int capacity)
		{
			NumbersInstantiated = new List<GameObject> ();
			this.capacity = capacity;
			this.origin = origin;
		}

		public void Remove(int goId)
		{
			NumbersInstantiated.Remove (NumbersInstantiated.Where (go => go.GetInstanceID () == goId).FirstOrDefault());
		}
	}
}

