//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Collections;

using UnityEngine;
  
namespace AssemblyCSharp
{
	public static class Grid
	{
		private static List<Column> columns = new List<Column>();

		public static bool AnyOpenSpaces
		{
			get
			{
				return columns.Any(c => c.OpenSpaces);
			}
		}

		public static void Resize(Vector2 desiredDims, float originY, float prefabWidth)
		{
			columns = new List<Column>();

			float originX = -((desiredDims.x * prefabWidth) / 2);

			originX += prefabWidth / 2;

			for (int i = 0; i < desiredDims.x; i++)
			{

				columns.Add (new Column (new Vector3 (originX, originY), Convert.ToInt32 (desiredDims.y)));
				originX += prefabWidth;
			}
		}

		public static void Add(GameObject go)
		{
			Column columnWithOpenSpace = columns.FirstOrDefault (c => c.OpenSpaces);
			if (columnWithOpenSpace != null)
				columnWithOpenSpace.Add (go);//go should be instantiated at this point
		}

	
	}
}