//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using UnityEngine;

namespace AssemblyCSharp
{
	public class NextNumberDto
	{
		public string Color_ { get; private set; }
		public string Shape { get; private set; }
		public int Number{ get; private set; }
		public Sprite Sprite_{ get; private set; }

		public NextNumberDto (string c, string s, Sprite sp, int i)
		{
			Color_ = c;
			Shape = s;
			Sprite_ = sp;
			Number = i;
		}
	}
}

